name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch, if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        working-directory: frontend  # Navigate to the frontend directory
        run: npm install

      - name: Build
        env:
          CI: false  # Disable treating warnings as errors
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_STADIA_MAPS_API_KEY: ${{ secrets.REACT_APP_STADIA_MAPS_API_KEY }}
        working-directory: frontend  # Navigate to the frontend directory
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build  # Path to the build output
