name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch, if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'  # or your preferred Node version

      - name: Install dependencies
        run: |
          cd frontend  # Navigate to the frontend directory
          npm install

      - name: Build
        env:
          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
        run: |
          cd frontend  # Navigate to the frontend directory
          npm run build

      - name: Deploy
        uses: JamesIArmes/github-pages-deploy-action@4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build  # Path to the build directory
